name: build-images-action

permissions:
  contents: read

on:
  push:
    branches:
    - 'main'

jobs:
  build_ipxe-builder:
    name: build ipxe-builder image
    if: github.repository == 'metal3-io/utility-images'
    uses: metal3-io/project-infra/.github/workflows/container-image-build.yml@main
    with:
      image-name: 'ipxe-builder'
      pushImage: true
      dockerfile-directory: ipxe-builder
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  build_fake-ipa:
    name: build fake-ipa image
    if: github.repository == 'metal3-io/utility-images'
    uses: metal3-io/project-infra/.github/workflows/container-image-build.yml@main
    with:
      image-name: 'fake-ipa'
      pushImage: true
      dockerfile-directory: fake-ipa
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
